### ISSUE TITLE
Behat version 3.1.0

### ISSUE THREAD

**Issue by yael-lorenzo** [allure-framework/allure-behat#6]
When would it be ready for Behat version 3.1.0?
 
 Problem 1
    - Installation request for allure-framework/allure-behat 1.0.0 -> satisfiable by allure-framework/allure-behat[1.0.0].
    - allure-framework/allure-behat 1.0.0 requires behat/behat ~2.4 -> satisfiable by behat/behat[2.5.x-dev, v2.4.0, v2.4.0beta1, v2.4.0beta2, v2.4.0beta3, v2.4.0beta4, v2.4.0beta5, v2.4.1, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.5.0, v2.5.1, v2.5.2, v2.5.3, v2.5.4, v2.5.5] but these conflict with your requirements or minimum-stability.

**Comment by eduard-sukharev** [comment]
It probably won't. We don't use behat 3 yet, so we don't have the need for it.

You could add the required support yourself and make a pull request. I think it should be quite straightforward and might even coexist with behat2 implementation.

**Comment by yael-lorenzo** [comment]
Hi Eduard. I understand. I thought the same about the PR. I need to find some time.
Thank you for the quick response.
